/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkoutsRouteImport } from './routes/workouts'
import { Route as WorkoutRouteImport } from './routes/workout'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProRouteImport } from './routes/pro'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkoutSummaryRouteImport } from './routes/workout.summary'
import { Route as SkillsSlugRouteImport } from './routes/skills.$slug'
import { Route as ApiPublicCoachRouteImport } from './routes/api/public/coach'

const WorkoutsRoute = WorkoutsRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutRoute = WorkoutRouteImport.update({
  id: '/workout',
  path: '/workout',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProRoute = ProRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutSummaryRoute = WorkoutSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => WorkoutRoute,
} as any)
const SkillsSlugRoute = SkillsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SkillsRoute,
} as any)
const ApiPublicCoachRoute = ApiPublicCoachRouteImport.update({
  id: '/api/public/coach',
  path: '/api/public/coach',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coach': typeof CoachRoute
  '/onboarding': typeof OnboardingRoute
  '/pro': typeof ProRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/skills': typeof SkillsRouteWithChildren
  '/workout': typeof WorkoutRouteWithChildren
  '/workouts': typeof WorkoutsRoute
  '/skills/$slug': typeof SkillsSlugRoute
  '/workout/summary': typeof WorkoutSummaryRoute
  '/api/public/coach': typeof ApiPublicCoachRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coach': typeof CoachRoute
  '/onboarding': typeof OnboardingRoute
  '/pro': typeof ProRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/skills': typeof SkillsRouteWithChildren
  '/workout': typeof WorkoutRouteWithChildren
  '/workouts': typeof WorkoutsRoute
  '/skills/$slug': typeof SkillsSlugRoute
  '/workout/summary': typeof WorkoutSummaryRoute
  '/api/public/coach': typeof ApiPublicCoachRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/coach': typeof CoachRoute
  '/onboarding': typeof OnboardingRoute
  '/pro': typeof ProRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/skills': typeof SkillsRouteWithChildren
  '/workout': typeof WorkoutRouteWithChildren
  '/workouts': typeof WorkoutsRoute
  '/skills/$slug': typeof SkillsSlugRoute
  '/workout/summary': typeof WorkoutSummaryRoute
  '/api/public/coach': typeof ApiPublicCoachRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/coach'
    | '/onboarding'
    | '/pro'
    | '/profile'
    | '/progress'
    | '/skills'
    | '/workout'
    | '/workouts'
    | '/skills/$slug'
    | '/workout/summary'
    | '/api/public/coach'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/coach'
    | '/onboarding'
    | '/pro'
    | '/profile'
    | '/progress'
    | '/skills'
    | '/workout'
    | '/workouts'
    | '/skills/$slug'
    | '/workout/summary'
    | '/api/public/coach'
  id:
    | '__root__'
    | '/'
    | '/coach'
    | '/onboarding'
    | '/pro'
    | '/profile'
    | '/progress'
    | '/skills'
    | '/workout'
    | '/workouts'
    | '/skills/$slug'
    | '/workout/summary'
    | '/api/public/coach'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoachRoute: typeof CoachRoute
  OnboardingRoute: typeof OnboardingRoute
  ProRoute: typeof ProRoute
  ProfileRoute: typeof ProfileRoute
  ProgressRoute: typeof ProgressRoute
  SkillsRoute: typeof SkillsRouteWithChildren
  WorkoutRoute: typeof WorkoutRouteWithChildren
  WorkoutsRoute: typeof WorkoutsRoute
  ApiPublicCoachRoute: typeof ApiPublicCoachRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workouts': {
      id: '/workouts'
      path: '/workouts'
      fullPath: '/workouts'
      preLoaderRoute: typeof WorkoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout': {
      id: '/workout'
      path: '/workout'
      fullPath: '/workout'
      preLoaderRoute: typeof WorkoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro': {
      id: '/pro'
      path: '/pro'
      fullPath: '/pro'
      preLoaderRoute: typeof ProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout/summary': {
      id: '/workout/summary'
      path: '/summary'
      fullPath: '/workout/summary'
      preLoaderRoute: typeof WorkoutSummaryRouteImport
      parentRoute: typeof WorkoutRoute
    }
    '/skills/$slug': {
      id: '/skills/$slug'
      path: '/$slug'
      fullPath: '/skills/$slug'
      preLoaderRoute: typeof SkillsSlugRouteImport
      parentRoute: typeof SkillsRoute
    }
    '/api/public/coach': {
      id: '/api/public/coach'
      path: '/api/public/coach'
      fullPath: '/api/public/coach'
      preLoaderRoute: typeof ApiPublicCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SkillsRouteChildren {
  SkillsSlugRoute: typeof SkillsSlugRoute
}

const SkillsRouteChildren: SkillsRouteChildren = {
  SkillsSlugRoute: SkillsSlugRoute,
}

const SkillsRouteWithChildren =
  SkillsRoute._addFileChildren(SkillsRouteChildren)

interface WorkoutRouteChildren {
  WorkoutSummaryRoute: typeof WorkoutSummaryRoute
}

const WorkoutRouteChildren: WorkoutRouteChildren = {
  WorkoutSummaryRoute: WorkoutSummaryRoute,
}

const WorkoutRouteWithChildren =
  WorkoutRoute._addFileChildren(WorkoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoachRoute: CoachRoute,
  OnboardingRoute: OnboardingRoute,
  ProRoute: ProRoute,
  ProfileRoute: ProfileRoute,
  ProgressRoute: ProgressRoute,
  SkillsRoute: SkillsRouteWithChildren,
  WorkoutRoute: WorkoutRouteWithChildren,
  WorkoutsRoute: WorkoutsRoute,
  ApiPublicCoachRoute: ApiPublicCoachRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
